-- Migration for initializing Task table and sequence

-- Sequence for task IDs
CREATE SEQUENCE SEQ_TASK
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Table definition
CREATE TABLE TB_TASK (
    ID NUMBER(19) NOT NULL,
    TITULO VARCHAR2(150) NOT NULL,
    DESCRICAO VARCHAR2(2000),
    STATUS VARCHAR2(20),
    DATA_CRIACAO TIMESTAMP WITH TIME ZONE NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP WITH TIME ZONE,
    USUARIO_ATUALIZACAO VARCHAR2(100),
    CONSTRAINT PK_TB_TASK PRIMARY KEY (ID)
);

-- Index to speed up queries by status
CREATE INDEX IDX_TASK_STATUS ON TB_TASK (STATUS);
